# Adjusting args to tekton-results namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-watcher
  namespace: tekton-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
        - name: watcher
          args:
            [
              "-api_addr",
              "tekton-results-api-service.tekton-results.svc.cluster.local:8080",
              "-auth_mode",
              "token",
            ]
          resources:
            requests:
              cpu: 5m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 2Gi
          securityContext:
            readOnlyRootFilesystem: true
